name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install npm packages
      uses: bahmutov/npm-install@v1

    - name: run standard
      run: npx ts-standard
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: download roblox install script
      run: Invoke-WebRequest -Uri "https://raw.githubusercontent.com/OrbitalOwen/roblox-win-installer/master/install.py" -OutFile install.py

    - name: download settings file
      run: Invoke-WebRequest -Uri "https://raw.githubusercontent.com/OrbitalOwen/roblox-win-installer/master/GlobalSettings_13.xml" -OutFile GlobalSettings_13.xml

    - name: install pip deps
      run: pip install wget psutil

    - name: install roblox
      run: python install.py "${{ secrets.ROBLOSECURITY }}"

    - name: install npm packages
      uses: bahmutov/npm-install@v1

    - name: build game
      run: npx rbxtsc --type=game

    - name: install foreman
      uses: rojo-rbx/setup-foreman@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: install foreman packages (rojo, run-in-roblox)
      run: foreman install

    - name: run rojo build
      run: rojo build -o ./tests.rbxlx

    - name: run tests
      run: run-in-roblox --place ./tests.rbxlx --script bin/tests.server.lua

